name: GitHub pages with Marp

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  page_build:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: docker run --rm -v $PWD:/home/marp/app/ -e LANG=$LANG -e MARP_USER="$(id -u):$(id -g)" marpteam/marp-cli -I slides -o build --theme-set theme/gttmy-basic.css
      - name: Index
        run: docker run --rm -v $PWD:/data --user "$(id -u):$(id -g)" pandoc/core -f markdown -t html README.md > build/index.html
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          branch: gh-pages
          folder: build
